# Generated by Django 5.2.5 on 2025-09-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("queued", "Queued"),
                            ("assigned", "Assigned"),
                            ("printing", "Printing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("items", models.JSONField(blank=True, default=list)),
                ("assigned_printer_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Printable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("price_cents", models.PositiveIntegerField()),
                ("stl", models.FileField(blank=True, null=True, upload_to="stl/")),
                ("color", models.CharField(blank=True, default="", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("status", models.CharField(default="idle", max_length=16)),
                ("last_ping_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_printer",
                        to="core.order",
                    ),
                ),
            ],
        ),
    ]
