# Generated by Django 5.2.5 on 2025-09-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_printables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printable",
            name="price_cents",
        ),
    ]
