# Generated by Django 5.2.5 on 2025-09-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_printable_price_cents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printable",
            name="sku",
        ),
    ]
