# Generated by Django 5.2.5 on 2025-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_printable_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
